options:
  precache_lxc:
    type: string
    default: ""
    description: should we precache lxc?  yes or empty
  tmpfs_size:
    type: string
    default: ""
    description: size of tmpfs partition to use for lxc... formatted like "5g"
  juju_environment:
    type: string
    default: ""
    description: juju environment to use for testing charms
