options:
  tools:
    type: string
    default: git gcc make bzr
    description: Tooling to deploy alongside jenkins
  release:
    type: string
    default: distro
    description: |
     Source of Jenkins, options include:
     - distro: only use the Ubuntu distribution - this
       is the default and only works on Oneiric.
     - lts: use the most recent Jenkins LTS release.
     - trunk: use the most recent Jenkins release.
  username:
    type: string
    default: admin
    description: Admin user username - used to manage
      slave nodes so please don't change in Jenkins.
  password:
    type: string
    default: admin
    description: Admin user password - used to manage
      slave nodes so please don't change in Jenkins.
  tmpfs_size:
    type: string
    default: 5g
    description: size of tmpfs partition to use for lxc
  api_token:
    type: string
    default: ""
    description: token used to kick off builds using the jenkins api (default is to create new)
  test_charm:
    type: string
    default: ""
    description: kick off a test for this charm
  add_charm:
    type: string
    default: ""
    description: create a new job for this launchpad branch
