options:
  tools:
    type: string
    default: git gcc make bzr
    description: Tooling to deploy alongside jenkins
  release:
    type: string
    default: distro
    description: |
     Source of Jenkins, options include:
     - distro: only use the Ubuntu distribution - this
       is the default and only works on Oneiric.
     - lts: use the most recent Jenkins LTS release.
     - trunk: use the most recent Jenkins release.
  username:
    type: string
    default: admin
    description: Admin user username - used to manage
      slave nodes so please don't change in Jenkins.
  password:
    type: string
    default: admin
    description: Admin user password - used to manage
      slave nodes so please don't change in Jenkins.
  plugins:
    type: string
    default: ""
    description: Space separated list of plugins to install
  plugins-site:
    type: string
    default: "https://updates.jenkins-ci.org/"
    description: Site to download plugin .hpi files from.
  plugins-check-certificate:
    type: string
    default: "yes"
    description: Set to no to allow downloading from an invalid https site.
  remove-unlisted-plugins:
    type: string
    default: "no"
    description: |
      Set this to yes to remove any plugins not listed in plugins
      from the installation.
  tmpfs_size:
    type: string
    default: ""
    description: size of tmpfs partition to use for lxc... formatted like "5g"
  test_series:
    type: string
    default: "oneiric"
    description: series to test
  test_charm:
    type: string
    default: ""
    description: kick off a test for this charm
  add_charm:
    type: string
    default: ""
    description: create a new job for this launchpad branch
