juju:
  tmpfs_size: 5g
  #juju_origin:
  juju_environment: |
    default: local
    environments:
      local:
        type: local
        data-dir: /var/lib/jenkins/.juju/local-oneiric
        admin-secret: abcdefghijklmnopqrstuvwxyz1234567890
        control-bucket: local-oneiric-bucket
        default-series: oneiric
        juju-origin: ppa
      local:
        type: local
        data-dir: /var/lib/jenkins/.juju/local-precise
        admin-secret: 0abcdefghijklmnopqrstuvwxyz123456789
        control-bucket: local-precise-bucket
        default-series: precise
        juju-origin: ppa
      ec2:
        type: ec2
        admin-secret: abcdefghijklmnopqrstuvwxyz1234567890
        control-bucket: foo-bucket
        default-series: precise
        juju-origin: ppa
